### ISSUE TITLE
Could HCTR2 be used on Linux 4.19.y kernel?

### ISSUE THREAD

**Issue by LeviMarvin** [google/hctr2#48]
The HCTR2 encryption mode could be used on Linux 4.19.y kernel? I have tried to backport this, but I have problems for applying changes into `aes-modes.S` file.

Please see my kernel repository: https://github.com/LeviMarvin/kernel_xiaomi_alioth

**Comment by ebiggers** [comment]
Anything is possible, it is just code :-)

But, I don't think you should bother with this.  HCTR2 support was backported to 5.10 and 5.15 in the Android Common Kernels.  I don't think it's worth going any further back.  As with any kernel patches, the farther back you go, the more conflicts you run into.

**Comment by LeviMarvin** [comment]
that's too bad! 5.15 is also newer kernel! Most people have not the newer device which running 5.15 kernel.

**Comment by ciphergoth** [comment]
We would welcome patches but we don't plan to work on it so I don't want to leave this as an open issue - thanks!
